#let dosen = (
  SD: "Prof. Ir. Supeno Djanali, M.Sc., Ph.D.",
  HT: "Prof. Ir. Handayani Tjandrasa, M.Sc., Ph.D.",
  RS: "Prof. Drs.Ec. Ir. Riyanarto Sarno, M.Sc., Ph.D.",
  JL: "Prof. Dr. Ir. Joko Lianto Buliali, M.Sc.",
  ST: "Ir. Siti Rochimah, M.T., Ph.D.",
  VH: "Victor Hariadi, S.Si., M.Kom.",
  RL: "Rully Soelaiman, S.Kom., M.Kom.",
  YP: "Dr. Yudhi Purwananto, S.Kom., M.Kom.",
  NS: "Prof. Dr.Eng. Nanik Suciati, S.Kom., M.Kom.",
  AS: "Dr. Ahmad Saikhu, S.Si., M.T.",
  WS: "Dr. Wahyu Suadi, S.Kom., M.Kom.",
  DS: "Dr. Dwi Sunaryono, S.Kom., M.Kom.",
  AZ: "Prof. Dr. Agus Zainal Arifin, S.Kom., M.Kom.",
  IS: "Ir. Misbakhul Munir Irfan Subakti, S.Kom, M.Sc., M.Phil",
  FB: "Fajar Baskoro, S.Kom., M.T.",
  DO: "Prof. Daniel Oranova Siahaan, S.Kom., M.Sc., PD.Eng.",
  TA: "Prof. Tohari Ahmad, S.Kom., MIT., Ph.D.",
  BA: "Dr. Bilqis Amaliah, S.Kom., M.Kom.",
  CF: "Prof. Dr.Eng. Chastine Fatichah, S.Kom., M.Kom.",
  SR: "Sarwosri, S.Kom., M.T.",
  IM: "Imam Kuswardayan, S.Kom., M.T.",
  RM: "Royyana Muslim Ijtihadie, S.Kom., M.Kom., Ph.D.",
  DH: "Dr.Eng. Darlis Herumurti, S.Kom., M.Kom.",
  DP: "Prof. Dr. Ir. Diana Purwitasari, S.Kom., M.Sc.",
  UY: "Dr. Ir. Umi Laili Yuhana, S.Kom., M.Sc.",
  AM: "Ir. Ary Mazharuddin Shiddiqi, S.Kom., M.Comp.Sc., Ph.D.",
  AY: "Dr. Anny Yuniarti, S.Kom, M.Comp.Sc.",
  AW: "Ir. Arya Yudhi Wijaya, S.Kom., M.Kom.",
  RA: "Dr.Eng. Radityo Anggoro, S.Kom., M.Sc.",
  RN: "Ratih Nur Esti Anggraini, S.Kom., M.Sc., Ph.D.",
  AL: "Adhatus Solichah Ahmadiyah, S.Kom., M.Sc.",
  DA: "Dini Adni Navastara, S.Kom., M.Sc.",
  WN: "Wijayanti Nurul Khotimah, S.Kom., M.Sc., Ph.D.",
  NF: "Nurul Fajrin Ariyani, S.Kom., M.Sc.",
  MN: "Abdul Munif, S.Kom., M.Sc.Eng.",
  BJ: "Bagus Jati Santoso, S.Kom., Ph.D.",
  RJ: "Rizky Januar Akbar, S.Kom., M.Eng.",
  BS: "Dr. Baskoro Adi Pratomo., S.Kom., M.Kom.",
  HS: "Hudan Studiawan, S.Kom., M.Kom., Ph.D.",
  HF: "Hadziq Fabroyir, S.Kom., Ph.D.",
  SC: "Shintami Chusnul Hidayati, S.Kom., M.Sc., Ph.D.",
  AB: "Agus Budi Raharjo, S.Kom., M.Kom., Ph.D.",
  SA: "Siska Arifiani, S.Kom., M.Kom.",
  KR: "Dr. Kelly Rossa Sungkono, S.Kom., M.Kom.",
  AI: "Aldinata Rizky Revanda, S.Kom., M.Kom.",
  NZ: "Moch. Nafkhan Alzamzami, S.T., M.T.",
  BN: "Bintang Nuralamsyah, S.Kom., M.Kom.",
  HM: "Dr.Eng. Muhamad Hilmil Muchtar Aditya Pradana, S. Kom., M. Sc..",
  MK: "Imam Mustafa Kamal, S.ST., Ph.D.",
  IG: "Ilham Gurat Adillion, S.Kom., M.Eng.",
)